openapi: 3.0.0
info:
  title: STC Consumer Authentication API
  description: STChealth authentication API for consumers
  version: 0.0.2

paths:
  /test:
    get:
      tags:
        - STC Auth Services
      description: Test if the endpoint is up and running.
      responses:
        "200":
          description: 200 ok
        "500":
          description: 500 unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TestFunction.Arn}/invocations
        responses:
          "200":
            statusCode: "200"
          "500":
            statusCode: "500"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
  /token:
    get:
      tags:
        - STC Auth Services
      description: Generates access and refresh tokens for consume the services specified in the provided scope.
      parameters:
        - in: query
          name: grant_type
          schema:
            type: string
            enum:
              - authorization_code
              - refresh_token
        - in: query
          name: code
          schema:
            type: string
        - in: query
          name: redirect_uri
          schema:
            type: string
        - in: query
          name: client_id
          schema:
            type: string
        - in: query
          name: client_secret
          schema:
            type: string
      responses:
        "200":
          description: 200 ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenResponse"
        "400":
          description: 400 bad request
        "401":
          description: 401 unauthorized
        "500":
          description: 500 unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${TokenFunction.Arn}/invocations
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
          "401":
            statusCode: "401"
          "500":
            statusCode: "500"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
  /auth:
    get:
      tags:
        - STC Auth Services
      description: Initiates the STC authentication workflow.
      parameters:
        - in: query
          name: client_id
          schema:
            type: string
            example: clear2021
        - in: query
          name: response_type
          schema:
            type: string
            example: code
        - in: query
          name: state
          schema:
            type: string
            example: a5uIJ98fTgj
        - in: query
          name: redirect_uri
          schema:
            type: string
            example: "clearApp://callback#token=&refresh=&expires="
        - in: query
          name: scope
          schema:
            type: string
            example: COVID-19
        - in: query
          name: user_info
          schema:
            type: string
            example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AbWFpbC5jb20iLCJwYXNzd29yZCI6InVzaGpoJWhqc1U5MDhobW1scyNAa2phYm5sIiwiZ2VuZGVyIjoiTWFsZSIsImJpcnRoRGF0ZSI6IjA2LzIwLzE5ODAiLCJwaG9uZSI6IjYxODIzNDk4NzgiLCJhZGRyZXNzIjoiMTAwMDEgR2lsIEpyIExhbmUsIEhvdXN0b24sIFRleGFzLCA3NzA3NSJ9.BWVrrbOYfpaXyghxikGm78uV55viTL3ryLLOCa5mzrg
      responses:
        "200":
          description: 200 ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthResponse"
        "400":
          description: 400 bad request
        "401":
          description: 401 unauthorized
        "500":
          description: 500 unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDetail"
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthFunction.Arn}/invocations
        responses:
          "200":
            statusCode: "200"
          "400":
            statusCode: "400"
          "401":
            statusCode: "401"
          "500":
            statusCode: "500"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
components:
  schemas:
    TokenResponse:
      type: object
      properties:
        access_token:
          type: string
          description: The access token value.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        refresh_token:
          type: string
          description: The refresh token to renew the access token.
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
        token_type:
          type: string
          description: Type of the token is set to "Bearer"
          example: Bearer
        expires_in:
          type: integer
          description: The lifetime in seconds of the access token
          example: 3600
        scope:
          type: string
          description: Returned scope for the token
          example: CREATE
    AuthResponse:
      type: object
      properties:
        redirect:
          type: string
          description: Redirect instruction to get back to the consumer application
          example: "clearApp://callback#code=eyJhbGciOi&state=0b24sIFRle"
    ErrorDetail:
      type: object
      properties:
        code:
          title: Error Code
          type: integer
          description: API Specific Error Code
          example: 5001
        message:
          title: Error Message
          type: string
          description: Detailed Error Message
          example: "An error ocurred when trying to connect to the database"
