AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "This is just a sample template"
Resources:
  NullResource:
    Type: "Custom::NullResource"
    Condition: HasNot
